name: CWPlugin
version: 1.0
main: org.kripaar.cwplugin.CWPlugin
commands:
  kripaars-ts-test:
    description: Testing Command
    usage: /kripaars-ts-test
  kripaars-re-register:
    description: Save Block at the position sender looking at.
    usage: /kripaars-re-register
  kripaars-re-remove:
    description: Unregister Block at the position sender looking at.
    usage: /kripaars-re-remove
  kripaars-bw-start:
    description: Start a Bed War game.
    usage: /kripaars-bw-start
  kripaars-bw-stop:
    description: End a Bed War Game.
    usage: /kripaars-bw-stop